GET http://localhost:3000/system/version

###
POST http://localhost:3000/system/log/6000/4
###
GET http://localhost:3000/content/getWaterHeaterInfo

###
GET http://localhost:3000/light

###
POST http://localhost:3000/light/45/On

###
GET http://localhost:3000/boiler
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImFkbWluIiwiaWF0IjoxNTU2OTY0NTYxLCJleHAiOjE1NTY5NjgxNjF9.aDCrZui4FlbaphPhblBPmcb7ayQb5h1_G7bTin4XK1I

###
POST http://localhost:3000/light/16/Toggle

###

POST http://localhost:3000/auth/login
content-type: application/json

{"name": "admin", "password": "admin"}
